sudo: required

language: go
go_import_path: github.com/ExpdiaDotCom/haystack-client-go

dist: trusty

matrix:
  include:
  - go: 1.9

services:
  - docker

addons:
  hosts:
    - kafkasvc
    - haystack_agent
    - haystack_collector

before_script:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - sudo unzip -o protoc-3.3.0-linux-x86_64.zip -d /usr/local bin/protoc
  - rm -f protoc-3.3.0-linux-x86_64.zip
  - curl https://glide.sh/get | sh

script:
  - make glide test validate integration_test

notifications:
  email:
    - haystack-notifications@expedia.com
